BOB-5-AST-Architecture
BobryPb/Parsobober pull request #3
Opened 2024-04-08 12:01 UTC by FilipDrazba

2024-04-08 12:33 UTC, pzajaczkowski requested changes

2024-04-08 12:33 UTC, pzajaczkowski commented on src/Pkb/Parsobober.Pkb.Ast/AstNodes/TreeNode.cs
> +public class TreeNode(int lineNumber, EntityType type)
Filip, wydaje mi się, że najlepszym rozwiązaniem problemu z dostępnością publicznych setterów jest użycie wzorca budowiczniczy. Dzięki niemu klasę TreeNode można zmienić na record, lub zrobić zwykłe propy z initem, bo zrobione node nie ulegną już zmianie.

https://refactoring.guru/design-patterns/builder/csharp/example

2024-04-08 12:47 UTC, pzajaczkowski requested changes

2024-04-08 12:47 UTC, pzajaczkowski commented on src/Pkb/Parsobober.Pkb.Ast/AstNodes/Ast.cs
> +    private TreeNode? Root
Podobna sytuacja, imo drzewo powinno samo się "zakorzenić" i w konstruktorze samemu ustawia jakiś node typu "program" czy coś ten teges.

```
public TreeNode Root { get; init; }
```
I można wtedy wywalić resztę _root i SetRoot

2024-04-08 12:47 UTC, pzajaczkowski commented on src/Pkb/Parsobober.Pkb.Ast/AstNodes/Ast.cs
> +    public void SetRoot(TreeNode node)
Tutaj w parametrze podałeś TreeNode, więc w c# nie mógłbyś nigdy przekazać nulla co oznacza, że ten setter co wyrzuca exception nigdy by się nie włączył

2024-04-08 12:47 UTC, pzajaczkowski commented on src/Pkb/Parsobober.Pkb.Ast/AstNodes/Ast.cs
> +    public TreeNode? GetRoot()
Jeżeli byłby publiczny prop po zmianach to ta metoda też nie potrzebna

2024-04-08 12:47 UTC, pzajaczkowski commented on src/Pkb/Parsobober.Pkb.Ast/AstNodes/IAst.cs
> +public interface IAst
Do dostosowania po zmianach w związanych z rootem

2024-04-09 10:30 UTC, pzajaczkowski approved these changes

2024-04-09 10:56 UTC, maksimowiczm approved these changes

2024-04-09 10:56 UTC, merged