[BOB-17] Implement IPkbCreator
BobryPb/Parsobober pull request #6
Opened 2024-04-13 12:05 UTC by pzajaczkowski

2024-04-15 19:34 UTC, maksimowiczm requested changes

2024-04-15 19:34 UTC, maksimowiczm commented on src/Pkb/Parsobober.Pkb.Relations/Implementations/ModifiesRelation.cs
> +        if (modifier.Type.IsStatement() == false || variable.Type != EntityType.Variable)
Why there is method `IsStatement` but not `IsVariable`

2024-04-15 19:34 UTC, maksimowiczm commented on src/Pkb/Parsobober.Pkb.Relations/Implementations/ModifiesRelation.cs
> +                $"At least one of provided nodes type: {modifier.Type}, {variable.Type} is different than any of required: {EntityType.Statement} types or {EntityType.Variable}.");
Is there any reason why we can't tell which one has invalid type and pass it as a message?

2024-04-15 19:34 UTC, maksimowiczm commented on src/Pkb/Parsobober.Pkb.Relations/Implementations/FollowsRelation.cs
> +        if (node.Type.IsStatement() == false || parent.Type.IsStatement() == false)
don't do `smth == false`

2024-04-15 19:34 UTC, maksimowiczm commented on src/Pkb/Parsobober.Pkb.Relations/Implementations/FollowsRelation.cs
> +using System.Xml;
unused using

2024-04-15 19:34 UTC, maksimowiczm commented on src/Pkb/Parsobober.Pkb.Relations/Implementations/ParentRelation.cs
> +    private readonly Dictionary<int, int> _parentsDictionary = new();
Parent can only have one child.

2024-04-16 11:00 UTC, pzajaczkowski commented on src/Pkb/Parsobober.Pkb.Relations/Implementations/ModifiesRelation.cs
> +    IProgramContextAccessor programContext
unobvious hint for klaudia to use it

2024-04-16 13:59 UTC, maksimowiczm approved these changes

2024-04-16 15:18 UTC, bciereszynski approved these changes

2024-04-16 16:58 UTC, merged